<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Core\Models\User;

class IrecProjectsSeeder extends Seeder
{
    public function run()
    {
        // Find sellers (user_type = 3)
        $sellers = User::where('user_type', 3)->get();
        
        if ($sellers->isEmpty()) {
            $this->command->warn('No sellers found with user_type = 3. Please create sellers first.');
            return;
        }

        $projects = [
            [
                'project_id' => 'IREC-329823',
                'project_name' => 'Benban Solar Park',
                'description' => 'Abu Zabal Landfill Gas Recovery and Flaring/Destruction Project. This project focuses on capturing and managing landfill gas emissions to reduce greenhouse gas emissions and generate renewable energy.',
                'energy_type' => 'solar',
                'country' => 'Egypt',
                'vintage_year' => 2024,
                'capacity_mwh' => 2000.00,
                'available_quantity_mwh' => 1500.00,
                'total_irecs' => 2000,
                'price_per_mwh' => 45.20,
                'vat_included' => true,
                'project_image' => 'projects/benban-solar-park.jpg',
                'project_link' => 'https://cdm.unfccc.int/Projects/Validation/DB/DJD59ANCGPEZYSFM8M09QLACCOY7LY/view.html',
                'status' => 'active',
                'coordinates_lat' => 30.0333,
                'coordinates_lng' => 31.2333,
                'address' => 'Abu Zabal Industrial Zone, Cairo Governorate',
                'city' => 'Cairo',
                'region' => 'Cairo Governorate',
                'postal_code' => '11511',
                'evident_id' => 'DAKAES10000',
                'issuance_date' => '2024-04-01',
                'expiry_date' => '2024-12-31',
                'technology' => 'Landfill Gas Management',
                'project_capacity' => 187000.00,
                'capacity_unit' => 'MWh',
            ],
            [
                'project_id' => 'IREC-329824',
                'project_name' => 'Zafarana Wind Farm',
                'description' => 'Large-scale wind energy project in the Zafarana region, harnessing the strong coastal winds to generate clean electricity.',
                'energy_type' => 'wind',
                'country' => 'Egypt',
                'vintage_year' => 2024,
                'capacity_mwh' => 2000.00,
                'available_quantity_mwh' => 1500.00,
                'total_irecs' => 2000,
                'price_per_mwh' => 45.20,
                'vat_included' => true,
                'project_image' => 'projects/project.jpg',
                'project_link' => null,
                'status' => 'active',
                'coordinates_lat' => 29.1167,
                'coordinates_lng' => 32.6500,
                'address' => 'Zafarana Wind Farm, Red Sea Governorate',
                'city' => 'Zafarana',
                'region' => 'Red Sea Governorate',
                'postal_code' => '84721',
                'evident_id' => 'DAKAES10001',
                'issuance_date' => '2024-03-15',
                'expiry_date' => '2024-12-31',
                'technology' => 'Wind Turbine',
                'project_capacity' => 150000.00,
                'capacity_unit' => 'MWh',
            ],
            [
                'project_id' => 'IREC-329825',
                'project_name' => 'Gulf of Suez Hydroelectric',
                'description' => 'Hydroelectric power generation project utilizing the natural flow of water in the Gulf of Suez region.',
                'energy_type' => 'hydro',
                'country' => 'Egypt',
                'vintage_year' => 2024,
                'capacity_mwh' => 2000.00,
                'available_quantity_mwh' => 1500.00,
                'total_irecs' => 2000,
                'price_per_mwh' => 45.20,
                'vat_included' => true,
                'project_image' => 'projects/gulf-of-suez-hydro.jpg',
                'project_link' => null,
                'status' => 'active',
                'coordinates_lat' => 28.5000,
                'coordinates_lng' => 33.0000,
                'address' => 'Gulf of Suez, Suez Governorate',
                'city' => 'Suez',
                'region' => 'Suez Governorate',
                'postal_code' => '43511',
                'evident_id' => 'DAKAES10002',
                'issuance_date' => '2024-02-20',
                'expiry_date' => '2024-12-31',
                'technology' => 'Hydroelectric Dam',
                'project_capacity' => 120000.00,
                'capacity_unit' => 'MWh',
            ],
            [
                'project_id' => 'IREC-329826',
                'project_name' => 'SolarTech Egypt',
                'description' => 'Advanced solar photovoltaic installation using cutting-edge technology for maximum energy efficiency.',
                'energy_type' => 'solar',
                'country' => 'Egypt',
                'vintage_year' => 2024,
                'capacity_mwh' => 2000.00,
                'available_quantity_mwh' => 1500.00,
                'total_irecs' => 2000,
                'price_per_mwh' => 45.20,
                'vat_included' => true,
                'project_image' => 'projects/project.jpg',
                'project_link' => null,
                'status' => 'active',
                'coordinates_lat' => 29.9792,
                'coordinates_lng' => 31.1342,
                'address' => 'SolarTech Industrial Park, Giza Governorate',
                'city' => 'Giza',
                'region' => 'Giza Governorate',
                'postal_code' => '12511',
                'evident_id' => 'DAKAES10003',
                'issuance_date' => '2024-01-10',
                'expiry_date' => '2024-12-31',
                'technology' => 'Solar Photovoltaic',
                'project_capacity' => 95000.00,
                'capacity_unit' => 'MWh',
            ],
            [
                'project_id' => 'IREC-329827',
                'project_name' => 'Morocco Solar Initiative',
                'description' => 'Large-scale solar power project in Morocco, contributing to the country\'s renewable energy goals.',
                'energy_type' => 'solar',
                'country' => 'Morocco',
                'vintage_year' => 2024,
                'capacity_mwh' => 2500.00,
                'available_quantity_mwh' => 2000.00,
                'total_irecs' => 2500,
                'price_per_mwh' => 48.50,
                'vat_included' => true,
                'project_image' => 'projects/project.jpg',
                'project_link' => null,
                'status' => 'active',
                'coordinates_lat' => 31.7917,
                'coordinates_lng' => -7.0926,
                'address' => 'Solar Complex, Marrakech-Safi Region',
                'city' => 'Marrakech',
                'region' => 'Marrakech-Safi',
                'postal_code' => '40000',
                'evident_id' => 'DAKAMA10000',
                'issuance_date' => '2024-03-01',
                'expiry_date' => '2024-12-31',
                'technology' => 'Concentrated Solar Power',
                'project_capacity' => 200000.00,
                'capacity_unit' => 'MWh',
            ],
            [
                'project_id' => 'IREC-329828',
                'project_name' => 'Tunisia Wind Energy',
                'description' => 'Coastal wind farm project in Tunisia, utilizing Mediterranean winds for sustainable energy production.',
                'energy_type' => 'wind',
                'country' => 'Tunisia',
                'vintage_year' => 2024,
                'capacity_mwh' => 1800.00,
                'available_quantity_mwh' => 1400.00,
                'total_irecs' => 1800,
                'price_per_mwh' => 46.80,
                'vat_included' => true,
                'project_image' => 'projects/project.jpg',
                'project_link' => null,
                'status' => 'active',
                'coordinates_lat' => 36.8065,
                'coordinates_lng' => 10.1815,
                'address' => 'Coastal Wind Farm, Tunis Governorate',
                'city' => 'Tunis',
                'region' => 'Tunis Governorate',
                'postal_code' => '1000',
                'evident_id' => 'DAKATN10000',
                'issuance_date' => '2024-02-15',
                'expiry_date' => '2024-12-31',
                'technology' => 'Offshore Wind Turbines',
                'project_capacity' => 135000.00,
                'capacity_unit' => 'MWh',
            ],
            [
                'project_id' => 'IREC-329829',
                'project_name' => 'Algeria Bioenergy Plant',
                'description' => 'Biomass energy facility converting agricultural waste into clean electricity.',
                'energy_type' => 'bio',
                'country' => 'Algeria',
                'vintage_year' => 2024,
                'capacity_mwh' => 1200.00,
                'available_quantity_mwh' => 900.00,
                'total_irecs' => 1200,
                'price_per_mwh' => 42.30,
                'vat_included' => true,
                'project_image' => 'projects/project.jpg',
                'project_link' => null,
                'status' => 'active',
                'coordinates_lat' => 36.7538,
                'coordinates_lng' => 3.0588,
                'address' => 'Bioenergy Industrial Complex, Algiers Province',
                'city' => 'Algiers',
                'region' => 'Algiers Province',
                'postal_code' => '16000',
                'evident_id' => 'DAKAAL10000',
                'issuance_date' => '2024-01-25',
                'expiry_date' => '2024-12-31',
                'technology' => 'Biomass Gasification',
                'project_capacity' => 85000.00,
                'capacity_unit' => 'MWh',
            ],
            [
                'project_id' => 'IREC-329830',
                'project_name' => 'Egypt Advanced Solar',
                'description' => 'Next-generation solar power plant using bifacial panels and smart tracking systems.',
                'energy_type' => 'solar',
                'country' => 'Egypt',
                'vintage_year' => 2024,
                'capacity_mwh' => 3000.00,
                'available_quantity_mwh' => 2500.00,
                'total_irecs' => 3000,
                'price_per_mwh' => 47.90,
                'vat_included' => true,
                'project_image' => 'projects/project.jpg',
                'project_link' => null,
                'status' => 'active',
                'coordinates_lat' => 26.8206,
                'coordinates_lng' => 30.8025,
                'address' => 'Advanced Solar Complex, Minya Governorate',
                'city' => 'Minya',
                'region' => 'Minya Governorate',
                'postal_code' => '61111',
                'evident_id' => 'DAKAES10004',
                'issuance_date' => '2024-04-15',
                'expiry_date' => '2024-12-31',
                'technology' => 'Bifacial Solar Panels',
                'project_capacity' => 250000.00,
                'capacity_unit' => 'MWh',
            ],
        ];

        foreach ($projects as $index => $project) {
            // Assign seller_id from available sellers (cycling through them)
            $sellerIndex = $index % $sellers->count();
            $project['seller_id'] = $sellers[$sellerIndex]->id;
            
            DB::table('tl_multivendor_irec_projects')->insert($project);
        }

        $this->command->info('IREC Projects seeded successfully!');
    }
}
